# Generated by Django 3.1.13 on 2021-08-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlxml', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='example',
            field=models.TextField(blank=True),
        ),
    ]
