# Generated by Django 3.1.13 on 2021-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlxml', '0003_auto_20210813_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='example_html',
            field=models.FileField(blank=True, upload_to='wlxml/tag/example/html/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='example_pdf',
            field=models.FileField(blank=True, upload_to='wlxml/tag/example/pdf/'),
        ),
    ]
