# Generated by Django 3.1.13 on 2021-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlxml', '0004_auto_20210814_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='example_txt',
            field=models.FileField(blank=True, upload_to='wlxml/tag/example/txt/'),
        ),
    ]
