# Generated by Django 4.1.9 on 2023-09-25 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0050_audience_woblink"),
        ("isbn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="isbn",
            name="bn_data",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="isbn",
            name="wl_data",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="isbn",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogue.book",
            ),
        ),
        migrations.AlterField(
            model_name="isbn",
            name="datestamp",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="isbn",
            name="form",
            field=models.CharField(
                blank=True, choices=[("pdf", "pdf")], max_length=32, null=True
            ),
        ),
    ]
