# Generated by Django 4.1.9 on 2023-09-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isbn", "0002_isbn_bn_data_isbn_wl_data_alter_isbn_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="isbn",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="isbn",
            name="bn_data",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="isbn",
            name="wl_data",
            field=models.TextField(blank=True),
        ),
    ]
