# Generated by Django 4.1.9 on 2023-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isbn", "0003_isbn_notes_alter_isbn_bn_data_alter_isbn_wl_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isbn",
            name="form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("html", "html"),
                    ("txt", "txt"),
                    ("pdf", "pdf"),
                    ("epub", "epub"),
                    ("mobi", "mobi"),
                    ("mp3", "mp3"),
                    ("paperback", "paperback"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
