# Generated by Django 4.1.9 on 2023-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isbn", "0004_alter_isbn_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isbn",
            name="form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("html", "html"),
                    ("txt", "txt"),
                    ("pdf", "pdf"),
                    ("epub", "epub"),
                    ("mobi", "mobi"),
                    ("mp3", "mp3"),
                    ("paperback", "paperback"),
                ],
                default="",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
