# Generated by Django 4.1.9 on 2023-09-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="wikisource",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
