# Generated by Django 4.1.9 on 2023-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0002_source_wikisource"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
