# Generated by Django 3.1.13 on 2021-12-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0006_auto_20210706_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('definition_json', models.TextField(blank=True)),
                ('status_json', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to='depot/logo')),
                ('file', models.FileField(blank=True, upload_to='depot/package/')),
                ('books', models.ManyToManyField(to='documents.Book')),
            ],
        ),
    ]
