# Generated by Django 4.1.9 on 2023-08-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0003_shop_rename_legimibookpublish_shopbookpublish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopbookpublish",
            name="shop",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="depot.shop"
            ),
        ),
    ]
