# Generated by Django 4.1.9 on 2023-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0004_shopbookpublish_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shop",
            name="publisher_handle",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
