# Generated by Django 4.1.9 on 2023-08-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0005_shop_name_shop_publisher_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="description_add",
            field=models.TextField(blank=True),
        ),
    ]
