# Generated by Django 4.1.9 on 2023-09-05 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0011_book_woblink_id"),
        ("depot", "0006_shop_description_add"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShopBookPublish",
            new_name="SiteBookPublish",
        ),
        migrations.RenameModel(
            old_name="ShopChunkPublish",
            new_name="SiteChunkPublish",
        ),
        migrations.RenameField(
            model_name="mediainserttext",
            old_name="shop",
            new_name="site",
        ),
        migrations.RenameField(
            model_name="pricelevel",
            old_name="shop",
            new_name="site",
        ),
        migrations.RenameField(
            model_name="shop",
            old_name="shop",
            new_name="site_type",
        ),
        migrations.RenameField(
            model_name="sitebookpublish",
            old_name="shop",
            new_name="site",
        ),
    ]
