# Generated by Django 4.1.9 on 2023-09-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0007_rename_shopbookpublish_sitebookpublish_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shop",
            new_name="Site",
        ),
    ]
