# Generated by Django 4.1.9 on 2023-09-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("depot", "0010_migrate_external_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitebookpublish",
            name="book",
        ),
        migrations.RemoveField(
            model_name="sitebookpublish",
            name="site",
        ),
    ]
