# Generated by Django 4.1.9 on 2023-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="approve_by_default",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
