# Generated by Django 4.1.9 on 2024-10-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("team", "0002_profile_approve_by_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "profil", "verbose_name_plural": "profil"},
        ),
        migrations.RenameField(
            model_name="presence",
            old_name="timestamp",
            new_name="since",
        ),
        migrations.AddField(
            model_name="presence",
            name="session_key",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presence",
            name="until",
            field=models.DateTimeField(db_index=True, default="1970-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="presence",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
