# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170207_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tutorial',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='tutorial_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tutorial_pl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
