# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20170411_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='help_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='tag',
            name='help_text_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='help_text_pl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
