# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20170411_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'index', 'label'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
