# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20170425_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-revision__created_at'], 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
