# Generated by Django 3.2.12 on 2022-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
