# Generated by Django 3.0.4 on 2020-03-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bookpublishrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chunk',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chunkchange',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chunkpublishrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chunktag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='imagechange',
            table=None,
        ),
        migrations.AlterModelTable(
            name='imagepublishrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='imagetag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
