# Generated by Django 3.0.4 on 2020-11-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20201102_1315'),
        ('documents', '0002_auto_20200322_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dc_slug',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.Book', to_field='slug', db_constraint=False),
        ),
    ]
