# Generated by Django 3.0.4 on 2020-11-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20201102_1315'),
        ('documents', '0004_auto_20201102_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catalogue_book',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_books', related_query_name='document_book', to='catalogue.Book', to_field='slug', db_constraint=False),
        ),
    ]
