# Generated by Django 3.1.13 on 2021-07-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20201102_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='_new_publishable',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='_published',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='_single',
            field=models.BooleanField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='_changed',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='_hidden',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='_new_publishable',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='_changed',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='_new_publishable',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='_published',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
