# Generated by Django 3.1.13 on 2022-03-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20210706_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dc',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
