# Generated by Django 4.1.9 on 2023-06-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_book_legimi_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
