# Generated by Django 4.1.9 on 2023-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.FileField(blank=True, upload_to="documents/cover"),
        ),
    ]
