# Generated by Django 4.1.9 on 2023-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_alter_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="woblink_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
