# Generated by Django 4.1.9 on 2023-09-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_book_woblink_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="legimi_id",
        ),
        migrations.RemoveField(
            model_name="book",
            name="woblink_id",
        ),
    ]
