# Generated by Django 4.1.9 on 2023-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_remove_book_legimi_id_remove_book_woblink_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunkchange",
            name="publishable",
            field=models.BooleanField(default=False, verbose_name="approved"),
        ),
        migrations.AlterField(
            model_name="imagechange",
            name="publishable",
            field=models.BooleanField(default=False, verbose_name="approved"),
        ),
    ]
