# Generated by Django 4.1.9 on 2024-01-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_project_logo_project_logo_mono"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
