# Generated by Django 4.1.9 on 2024-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_project_logo_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="can_sell",
            field=models.BooleanField(default=True, verbose_name="Do sprzedaży"),
        ),
        migrations.AddField(
            model_name="project",
            name="private_notes",
            field=models.TextField(blank=True, verbose_name="Prywatne notatki"),
        ),
    ]
