# Generated by Django 4.1.9 on 2024-10-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_project_can_sell_project_private_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="catalogue_book",
            new_name="dc_slug",
        ),
    ]
