# Generated by Django 4.1.9 on 2024-10-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0019_fk_uses_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="dc_slug",
            field=models.CharField(
                blank=True, editable=False, max_length=2048, null=True
            ),
        ),
    ]
