# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='_short_html',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='_short_html',
        ),
        migrations.RemoveField(
            model_name='image',
            name='_short_html',
        ),
    ]
