# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190307_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='_new_publishable',
            field=models.NullBooleanField(editable=False),
        ),
    ]
