# Generated by Django 3.0.4 on 2020-03-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Alive'), (2, 'Dead'), (3, 'Long dead'), (4, 'Unknown')], null=True),
        ),
    ]
