# Generated by Django 3.0.4 on 2020-04-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20200411_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='culturepl_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='gazeta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='pd_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
