# Generated by Django 3.0.4 on 2020-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20200415_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('authors', models.ManyToManyField(blank=True, to='catalogue.Author')),
                ('books', models.ManyToManyField(blank=True, to='catalogue.Book')),
            ],
        ),
    ]
