# Generated by Django 3.0.4 on 2020-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('last_name', 'first_name', 'year_of_death')},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='books',
        ),
        migrations.AddField(
            model_name='author',
            name='collections',
            field=models.ManyToManyField(blank=True, to='catalogue.Collection'),
        ),
        migrations.AddField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(blank=True, to='catalogue.Collection'),
        ),
    ]
