# Generated by Django 3.0.4 on 2020-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20200415_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gazeta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
