# Generated by Django 3.0.4 on 2020-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_book_gazeta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_de',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='name_lt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
