# Generated by Django 3.0.4 on 2020-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20200416_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='description_lt',
            field=models.TextField(blank=True),
        ),
    ]
