# Generated by Django 3.0.4 on 2020-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20200417_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='wikidata',
            field=models.CharField(blank=True, default='', help_text='If you have a Wikidata ID, like "Q1337", enter it and save.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='wikidata',
            field=models.CharField(blank=True, default='', help_text='If you have a Wikidata ID, like "Q1337", enter it and save.', max_length=255),
            preserve_default=False,
        ),
    ]
