# Generated by Django 3.0.4 on 2020-10-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20201027_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epoch',
            options={'verbose_name': 'epoch', 'verbose_name_plural': 'epochs'},
        ),
    ]
