# Generated by Django 3.0.4 on 2020-10-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20201027_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('collections', models.ManyToManyField(to='catalogue.Collection')),
                ('epochs', models.ManyToManyField(to='catalogue.Epoch')),
                ('genres', models.ManyToManyField(to='catalogue.Genre')),
                ('kinds', models.ManyToManyField(to='catalogue.Kind')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.WorkType')),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
    ]
