# Generated by Django 3.0.4 on 2020-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_workrate_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
