# Generated by Django 3.0.4 on 2020-10-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20201027_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrate',
            old_name='rate',
            new_name='per_normpage',
        ),
        migrations.AddField(
            model_name='workrate',
            name='per_verse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
