# Generated by Django 3.0.4 on 2020-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20201027_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrate',
            name='collections',
            field=models.ManyToManyField(blank=True, to='catalogue.Collection'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='epochs',
            field=models.ManyToManyField(blank=True, to='catalogue.Epoch'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='genres',
            field=models.ManyToManyField(blank=True, to='catalogue.Genre'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='kinds',
            field=models.ManyToManyField(blank=True, to='catalogue.Kind'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='per_normpage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='per_verse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
