# Generated by Django 3.0.4 on 2020-11-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20201027_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalogue.CollectionCategory')),
            ],
            options={
                'verbose_name': 'collection category',
                'verbose_name_plural': 'collection categories',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.CollectionCategory'),
        ),
    ]
