# Generated by Django 3.0.4 on 2020-11-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20201102_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('category', 'name'), 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='collectioncategory',
            options={'ordering': ('parent__name', 'name'), 'verbose_name': 'collection category', 'verbose_name_plural': 'collection categories'},
        ),
        migrations.AlterModelOptions(
            name='workrate',
            options={'ordering': ('priority',), 'verbose_name': 'work rate', 'verbose_name_plural': 'work rates'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ('name',), 'verbose_name': 'work type', 'verbose_name_plural': 'work types'},
        ),
        migrations.AlterField(
            model_name='author',
            name='collections',
            field=models.ManyToManyField(blank=True, to='catalogue.Collection', verbose_name='collections'),
        ),
        migrations.AlterField(
            model_name='author',
            name='culturepl_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='culture.pl link'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='description (de)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_lt',
            field=models.TextField(blank=True, verbose_name='description (lt)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gazeta_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='gazeta link'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, max_length=255, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='name (de)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_lt',
            field=models.CharField(blank=True, max_length=255, verbose_name='name (lt)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='author',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Alive'), (2, 'Dead'), (3, 'Long dead'), (4, 'Unknown')], null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='year of death'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='catalogue.Author', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translation', to='catalogue.Book', verbose_name='based on'),
        ),
        migrations.AlterField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(blank=True, to='catalogue.Collection', verbose_name='collections'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epochs',
            field=models.ManyToManyField(blank=True, to='catalogue.Epoch', verbose_name='epochs'),
        ),
        migrations.AlterField(
            model_name='book',
            name='estimate_source',
            field=models.CharField(blank=True, max_length=2048, verbose_name='source of estimates'),
        ),
        migrations.AlterField(
            model_name='book',
            name='estimated_chars',
            field=models.IntegerField(blank=True, null=True, verbose_name='estimated number of characters'),
        ),
        migrations.AlterField(
            model_name='book',
            name='estimated_verses',
            field=models.IntegerField(blank=True, null=True, verbose_name='estimated number of verses'),
        ),
        migrations.AlterField(
            model_name='book',
            name='gazeta_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='gazeta link'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='catalogue.Genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='book',
            name='kinds',
            field=models.ManyToManyField(blank=True, to='catalogue.Kind', verbose_name='kinds'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=255, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pd_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year of entry into PD'),
        ),
        migrations.AlterField(
            model_name='book',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='book',
            name='scans_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='scans source'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='text source'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(blank=True, related_name='translated_book_set', related_query_name='translated_book', to='catalogue.Author', verbose_name='translators'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.CollectionCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collectioncategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collectioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalogue.CollectionCategory', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='collections',
            field=models.ManyToManyField(blank=True, to='catalogue.Collection', verbose_name='collections'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='epochs',
            field=models.ManyToManyField(blank=True, to='catalogue.Epoch', verbose_name='epochs'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='genres',
            field=models.ManyToManyField(blank=True, to='catalogue.Genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='kinds',
            field=models.ManyToManyField(blank=True, to='catalogue.Kind', verbose_name='kinds'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='per_normpage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='per normalized page'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='per_verse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='per verse'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='workrate',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.WorkType', verbose_name='work type'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
