# Generated by Django 3.1.13 on 2021-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20201102_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='collectioncategory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
    ]
