# Generated by Django 4.0.6 on 2022-09-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_author_place_of_birth_author_place_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='free_license',
            field=models.BooleanField(default=False, verbose_name='free license'),
        ),
        migrations.AddField(
            model_name='book',
            name='polona_missing',
            field=models.BooleanField(default=False, verbose_name='missing on Polona'),
        ),
    ]
