# Generated by Django 4.0.6 on 2022-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_book_free_license_book_polona_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name_lt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name_pl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_lt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_pl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='author',
            name='place_of_birth_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of birth'),
        ),
        migrations.AddField(
            model_name='author',
            name='place_of_birth_lt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of birth'),
        ),
        migrations.AddField(
            model_name='author',
            name='place_of_birth_pl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of birth'),
        ),
        migrations.AddField(
            model_name='author',
            name='place_of_death_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of death'),
        ),
        migrations.AddField(
            model_name='author',
            name='place_of_death_lt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of death'),
        ),
        migrations.AddField(
            model_name='author',
            name='place_of_death_pl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of death'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_lt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
