# Generated by Django 4.0.6 on 2022-09-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_author_description_pl_author_first_name_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotableBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.book')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
