# Generated by Django 4.0.6 on 2022-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_notablebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata', models.CharField(blank=True, help_text='If you have a Wikidata ID, like "Q1337", enter it and save.', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('name_pl', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('name_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('name_lt', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('locative', models.CharField(blank=True, help_text='in…', max_length=255, verbose_name='locative')),
                ('locative_pl', models.CharField(blank=True, help_text='in…', max_length=255, null=True, verbose_name='locative')),
                ('locative_de', models.CharField(blank=True, help_text='in…', max_length=255, null=True, verbose_name='locative')),
                ('locative_lt', models.CharField(blank=True, help_text='in…', max_length=255, null=True, verbose_name='locative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_birth_de',
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_birth_lt',
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_birth_pl',
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_death',
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_death_de',
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_death_lt',
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_death_pl',
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_death'),
        ),
        migrations.AddField(
            model_name='author',
            name='year_of_birth_range',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='year of birth, range end'),
        ),
        migrations.AddField(
            model_name='author',
            name='year_of_death_range',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='year of death, range end'),
        ),
    ]
