# Generated by Django 4.0.6 on 2022-09-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_place_remove_author_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authors_born', to='catalogue.place', verbose_name='place of birth'),
        ),
        migrations.AddField(
            model_name='author',
            name='place_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authors_died', to='catalogue.place', verbose_name='place of death'),
        ),
    ]
