# Generated by Django 4.0.6 on 2022-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_author_place_of_birth_author_place_of_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AddField(
            model_name='author',
            name='year_of_birth_inexact',
            field=models.BooleanField(default=False, verbose_name='inexact'),
        ),
        migrations.AddField(
            model_name='author',
            name='year_of_death_inexact',
            field=models.BooleanField(default=False, verbose_name='inexact'),
        ),
    ]
