# Generated by Django 4.0.6 on 2022-09-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_alter_place_options_author_year_of_birth_inexact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='original publication year'),
        ),
    ]
