# Generated by Django 4.0.6 on 2022-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_book_original_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/author/'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo_attribution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='photo_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='plwiki',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
