# Generated by Django 4.0.6 on 2022-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_author_photo_author_photo_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
