# Generated by Django 4.0.6 on 2022-11-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='genitive',
            field=models.CharField(blank=True, help_text='utwory … (czyje?)', max_length=255, verbose_name='dopełniacz'),
        ),
        migrations.AddField(
            model_name='epoch',
            name='adjective_feminine_singular',
            field=models.CharField(blank=True, help_text='twórczość … Adama Mickiewicza', max_length=255, verbose_name='przymiotnik pojedynczy żeński'),
        ),
        migrations.AddField(
            model_name='epoch',
            name='adjective_nonmasculine_plural',
            field=models.CharField(blank=True, help_text='utwory … Adama Mickiewicza', max_length=255, verbose_name='przymiotnik mnogi niemęskoosobowy'),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_epoch_specific',
            field=models.BooleanField(default=False, help_text='Po wskazaniu tego gatunku, dodanie epoki byłoby nadmiarowe, np. „dramat romantyczny”'),
        ),
        migrations.AddField(
            model_name='genre',
            name='plural',
            field=models.CharField(blank=True, help_text='dotyczy gatunków', max_length=255, verbose_name='liczba mnoga'),
        ),
        migrations.AddField(
            model_name='kind',
            name='collective_noun',
            field=models.CharField(blank=True, help_text='np. „Liryka” albo „Twórczość dramatyczna”', max_length=255, verbose_name='określenie zbiorowe'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, help_text='for publication', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_de',
            field=models.TextField(blank=True, help_text='for publication', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_lt',
            field=models.TextField(blank=True, help_text='for publication', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_pl',
            field=models.TextField(blank=True, help_text='for publication', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(blank=True, help_text='private', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, help_text='private', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, help_text='private', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='collectioncategory',
            name='notes',
            field=models.TextField(blank=True, help_text='private', verbose_name='notes'),
        ),
    ]
