# Generated by Django 4.0.6 on 2022-12-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_author_genitive_epoch_adjective_feminine_singular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMonthlyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views_reader', models.IntegerField(default=0)),
                ('views_page', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.book')),
            ],
        ),
    ]
