# Generated by Django 4.0.6 on 2022-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_bookmonthlystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='monthly_views_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='monthly_views_reader',
            field=models.IntegerField(default=0),
        ),
    ]
