# Generated by Django 4.0.6 on 2022-12-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_book_monthly_views_page_book_monthly_views_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='description',
            field=models.TextField(blank=True, help_text='for publication', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='for publication', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='kind',
            name='description',
            field=models.TextField(blank=True, help_text='for publication', verbose_name='description'),
        ),
    ]
