# Generated by Django 4.0.6 on 2023-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_author_century_of_birth_author_century_of_death'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('usable', models.BooleanField()),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
