# Generated by Django 4.1.9 on 2023-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0046_thema"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="woblink",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
