# Generated by Django 4.1.9 on 2023-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0048_audience_alter_thema_options_thema_plural_thema_slug_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="thema",
            name="public_description",
            field=models.TextField(blank=True),
        ),
    ]
