# Generated by Django 4.1.9 on 2023-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0049_thema_public_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="audience",
            name="woblink",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
