# Generated by Django 4.1.9 on 2023-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0050_audience_woblink"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="plwiki",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
