# Generated by Django 4.1.9 on 2024-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0051_book_plwiki"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="thema",
            field=models.CharField(
                blank=True, help_text="Odpowiadający kwalifikator Thema.", max_length=32
            ),
        ),
    ]
