# Generated by Django 4.1.9 on 2024-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0052_genre_thema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thema",
            name="code",
            field=models.CharField(
                help_text="Używamy rozszerzenia <code>.WL-</code> do oznaczania własnych kodów.<br> Przykładowo, w przypadku potrzeby stworzenia nowej kategorii „insurekcja kościuszkowska”, można by ją utworzyć jako 3MLQ‑PL‑A.WL-A, czyli w ramach już istniejącej wyższej kategorii 3MLQ‑PL‑A „rozbiory Polski”.",
                max_length=128,
                unique=True,
            ),
        ),
    ]
