# Generated by Django 4.1.9 on 2024-08-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0053_alter_thema_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.FileField(blank=True, upload_to="catalogue/cover"),
        ),
    ]
