# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20170119_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='preview_html',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='preview_html_pl',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='preview_html',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='preview_html_pl',
        ),
    ]
