# Generated by Django 2.0.13 on 2019-10-02 12:24

import cover.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(storage=cover.models.OverwriteStorage(), upload_to='cover/image', verbose_name='file'),
        ),
    ]
