# Generated by Django 3.1.13 on 2022-02-25 14:31

import cover.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0002_auto_20191002_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cut_bottom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='cut_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='cut_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='cut_top',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='use_file',
            field=models.ImageField(default='', storage=cover.models.OverwriteStorage(), upload_to='cover/use', verbose_name='file for use'),
            preserve_default=False,
        ),
    ]
