# Generated by Django 3.1.13 on 2022-02-25 14:31

from django.db import migrations


def populate_use_file(apps, schema_editor):
    Image = apps.get_model('cover', 'Image')
    for img in Image.objects.all():
        img.use_file.save(
            "%d.jpg" % img.id,
            img.file
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0003_auto_20220225_1431'),
    ]

    operations = [
        migrations.RunPython(
            populate_use_file,
            migrations.RunPython.noop
        )
    ]
