# Generated by Django 3.2.12 on 2022-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0004_populate_use_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='download_url',
            field=models.URLField(blank=True, max_length=4096, null=True, unique=True, verbose_name='image download URL'),
        ),
    ]
