# Generated by Django 4.1.9 on 2024-10-21 13:31

import cover.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cover", "0006_image_example"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                max_length=1024,
                storage=cover.models.OverwriteStorage(),
                upload_to="cover/image",
                verbose_name="file",
            ),
        ),
    ]
